lib/manageiq/api/client.rb
lib/manageiq/api/client/version.rb
manageiq-api-client.gemspec
spec/manageiq/api/client_spec.rb

Changing Class references (not doc) from ManageIQ::Api::Client to ManageIQ::API::Client

Renaming ManageIQ::Api::Client to ManageIQ::API::Client

---

lib/manageiq-api-client.rb
lib/manageiq_api_client.rb

This is common in other gems to have various entrypoints that are named
reasonably.

Add alternate require files that match common patterns.

---

README.md

ManageIQ::API::Client.new(:url => ..., :user => ..., :password => ...)
Fixes #13

Fix for README.md, Authentication takes :user and not :username.

---

lib/manageiq/api/client/connection.rb

when doing deletes of resource via the DELETE action,
successful reponses have no content. We need to support
empty json responses.

Support empty json responses

---

lib/manageiq/api/client/resource.rb

Attributes are still stored in data hash for segregation but are also accessible via method:
```ruby
vm = miq.vms.search.last
vm.data["cpu_shares"]
or simply:
vm.cpu_shares
```
Fixes #8

Support accessing resource attributes directly

---

lib/manageiq/api/client/collection.rb
lib/manageiq/api/client/resource.rb

This will prevent us from finding constants like `::Settings` when trying to determine if `ManageIQ::API::Client::Collection::Settings` is defined already.
I ran into this while testing the gem in the context of the manageiq app.
When I tried to initialize a client, I got the following stacktrace with an error message indicating we attempted to call `.new` on the config gem global settings object.
```
/home/ncarboni/.gem/ruby/2.3.1/bundler/gems/manageiq-api-client-4bc859de2eb1/lib/manageiq/api/client/client.rb:56:in `collect'
/home/ncarboni/.gem/ruby/2.3.1/bundler/gems/manageiq-api-client-4bc859de2eb1/lib/manageiq/api/client/client.rb:56:in `load_collections'
/home/ncarboni/.gem/ruby/2.3.1/bundler/gems/manageiq-api-client-4bc859de2eb1/lib/manageiq/api/client/client.rb:30:in …
```

Disable ancestor constant search for collections and resources

---

manageiq-api-client.gemspec

This versioning was preventing us from bundling with ManageIQ
@abellotti @Fryguy please review

Remove dependency restrictions for json and more_core_extenstions

---

lib/manageiq/api/client/authentication.rb
lib/manageiq/api/client/client.rb
lib/manageiq/api/client/connection.rb

- Needed the Connection to leverage the authentication in the client object
- added the update_authentication() method in client
- updates authentication only after successful reconnect.
- Can also be used if user decides to use different token or different group for authorization.
Fixes #7

Added support for updating authentication

---

lib/manageiq/api/client/client.rb
lib/manageiq/api/client/collection.rb

- Bringing issue fixed by Adam in https://github.com/ManageIQ/manageiq-api-client/pull/19
supporting single string filter.
- Allow parsing of earlier API entrypoints where settings and identity are not returned.
/cc @carbonin issues we've hit today.

Fixes issue with single filter and working with earlier API server entrypoints

---

lib/manageiq/api/client/collection.rb
lib/manageiq/api/client/resource.rb

Since the dynamic subclass inherits from the base class, and the base
class is defined to be abstract with a raise in the initialize method,
then we can just let the methods live on the base class.  There is no
need to dynamically define them.

Simplify the creation of dynamic subclasses.

---

lib/manageiq/api/client.rb
lib/manageiq/api/client/connection.rb
lib/manageiq/api/client/mixins/custom_inspect_mixin.rb

Because the inspect method was overridden, Ruby's PP module (and by
extension pry's pretty printer) would not pretty print any objects
properly, instead leaving them on a single line which is hard to use.
This commit allows PP to work properly.
By happenstance it also greatly simplifies the CustomInspectMixin by
using the built-in pretty_print_inspect as the custom inspect method.
The removal of instance variables was the one feature that
CustomInspectMixin provided, but it turns out PP already has support for
that, so we can just use it.
Before
```text
> puts miq.vms.inspect
#<ManageIQ::API::Client::Collection::Vms:0x007fab1ffe2078 @name="vms", @href="http://localhost:3000/api/vms", @description="Virtual Machines", @actions=[]>
> puts miq.vms.pretty_inspect …
```

Add support for PP

---

lib/manageiq/api/client/resource.rb

while we were defaulting args to {}, we were not handling
case where the args were sent in as nil.

Handle case where nil was sent as an argument to the resource action

---

lib/manageiq/api/client/collection.rb
lib/manageiq/api/client/resource.rb

Now can pluck one or more attributes of a collection efficiently.
Examples:
- miq.vms.pluck(:id)
- miq.vms.pluck(:id, :name, :vendor)
Solves #33

Adding support for pluck

---

lib/manageiq/api/client/client.rb

Need to rename client's settings as it gets overritten by the settings collection, so the entrypoint's "settings" element is no longer accessible via the api client.

Rename client's settings to user_settings

---

lib/manageiq/api/client/error.rb

We need to enhance the Client to support Rails errors (they simply come in
as string) in addition to the API error signature.
- Before the fix
miq.get("bogus_collection")
NoMethodError: undefined method `values_at' for "Not Found":String
from /Users/abellotti/projects/manageiq-api-client/lib/manageiq/api/client/error.rb:23:in `update'
miq.error
=> nil
- After the fix.
miq.get("bogus_collection")
RuntimeError: Not Found
from /Users/abellotti/projects/manageiq-api-client/lib/manageiq/api/client/connection.rb:104:in `check_response'
miq.error
=> #<ManageIQ::API::Client::Error:0x007fcd274c77b8 @kind=nil, @klass=nil, @message="Not Found", @status=404>

Fix ManageIQ::API::Client::Error to support the Rails errors (routing, etc)

---

lib/manageiq/api/client/connection.rb

while this works, it is confusing to see in webmock stubs and such.
requests are made as:
```
http://localhost:3000/api/?attributes=authorization
```
with this fix they are just
```
http://localhost:3000/api?attributes=authorization
```

When fetching the entrypoint a / is appended to the URL.

---

manageiq-api-client.gemspec

Loosens AS dependency, as it doesn't need to restrict minor versions. This allows for us to try out the new Rails 5.1 beta.

Loosen ActiveSupport dependency

---

manageiq-api-client.gemspec

On second thought, this is better.
This still restricts the minor version as Rails doesn't actually follow
semver and no changes between minor versions is NOT guaranteed - yet
still allows for beta versions of the next minor to be used.

Restrict AS minor, but allow for prerelease

---

lib/manageiq/api/client/server_info.rb
spec/fixtures/api/responses/entrypoint.json
spec/manageiq/api/client_spec.rb

Enhanced ServerInfo to support the new _href entries.
Adds the following attributes:
- server_href
- zone_href
- region_href
Updated fixture so the new entries are exercised in the rspecs.
Updated client rspecs

Enhanced ServerInfo to support the new _href entries.

---

lib/manageiq/api/client/collection.rb
spec/fixtures/api/responses/sample_group_create.json
spec/fixtures/api/responses/single_group_query.json
spec/manageiq/api/collection_spec.rb

Enhancement to improve the query performed when the actions the collection need to be fetched.

Improve query used when fetching collection actions

---

lib/manageiq/api/client/collection.rb
spec/fixtures/api/responses/filter_vms_id_9999_not_found.json
spec/manageiq/api/collection_spec.rb

Instead, we need to raise when the result is a blank array
Add a new response JSON for this example
Partially reverts changes in 923267d9ef29b846210388334b57f70e02ad94cc
https://bugzilla.redhat.com/show_bug.cgi?id=1599754
Previously resulted inrequeueing due to error:
```
[----] I, [2019-02-18T20:02:25.832748 #16963:adcf64]  INFO -- : MIQ(MiqQueue#deliver) Message id: [99000000001518], Delivering...
[----] E, [2019-02-18T20:02:26.492599 #16963:adcf64] ERROR -- : An error occurred while invoking remote tasks...Requeueing for 1 minute from now.
[----] E, [2019-02-18T20:02:26.494510 #16963:adcf64] ERROR -- : [NoMethodError]: undefined method `id' for nil:NilClass  Method:[rescue in block in invoke_tasks_remote]
[----] E, [2019-02-18T20:02:26.494756 #16963:adcf64] ERROR -- : …
```

Raw query filtering by id doesn't raise when not found

---

manageiq-api-client.gemspec

Note, we should probably add appraisal gem to test multiple rails versions but this repo only uses AS::Concern and has very little need to test each version of rails.

Relax requirement as ActiveSupport::Concern is stable.

---

manageiq-api-client.gemspec

Json 2.1.0 throws _a lot_ of deprecation warnings on ruby 2.7
`~/.gems/2.7.0/gems/json-2.1.0/lib/json/common.rb:156: warning: Using the last argument as keyword parameters is deprecated`

Update the json gem to v2.3

---

.travis.yml
Gemfile

```
Post-install message from codeclimate-test-reporter:
Code Climate's codeclimate-test-reporter gem has been deprecated in favor of
our language-agnostic unified test reporter. The new test reporter is faster,
distributed as a static binary so dependency conflicts never occur, and
supports parallelized CI builds & multi-language CI configurations.
Please visit https://docs.codeclimate.com/v1.0/docs/configuring-test-coverage
for help setting up your CI process with our new test reporter.
```
it's marked work in progress because it depends on the addition of the token re: https://github.com/ManageIQ/azure-armrest/pull/403#issuecomment-754050779
@miq-bot add_label dependencies, test

remove deprecated codeclimate-test-reporter gem

---

CHANGELOG.md
lib/manageiq/api/client/version.rb

Release gem with new Faraday version (0.9 => 1.0) and added Rails 6.1 support
Rails comments:
- it supports Rails 6.0 and Rails 6.1
Faraday comments:
- miq_bot depends upon Faraday 0.9 (I haven't tested with 1.0 but this is a tangent)
- azure-sdk uses either 0.9 or 1.x.
- no other `Gemfile` or `*.gemspec` mention it

Release 0.3.6

---

manageiq-api-client.gemspec

Faraday 1.0.1 was released 3/29/2020
Faraday 1.10.3 was released 1/18/2023
(it is not in the new 2.x branch, but it is more up to date. following SemVer seemed like the least amount of work)
This resolves the following warnings
```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
```

Loosen faraday to 1.x

---

lib/manageiq/api/client/authentication.rb
lib/manageiq/api/client/connection.rb
spec/manageiq/api/authentication_spec.rb
spec/manageiq/api/client_spec.rb

This PR adds support for Bearer tokens when using an external auth system that requires them (such as OIDC).

Add Bearer token support

---

spec/fixtures/api/responses/filter_vms_id_9999_not_found.json

part of https://github.com/ManageIQ/manageiq/issues/21204

dropping lifecycle_event model

---

.github/workflows/ci.yaml
Gemfile
lib/manageiq/api/client.rb
lib/manageiq/api/client/connection.rb
manageiq-api-client.gemspec

https://github.com/ManageIQ/query_relation/pull/31 removes these same dependencies from query_relation
Before
======
```ruby
gem "manageiq-api-client"
```
```
bundle update
=> 26 gems
```
After
=====
```
bundle update
=> 12 gems
```

Drop More core extensions and active_support dependencies

---

.github/workflows/ci.yaml
Gemfile
lib/manageiq/api/client.rb
lib/manageiq/api/client/client.rb
lib/manageiq/api/client/connection.rb
lib/manageiq/api/client/resource.rb
manageiq-api-client.gemspec

Dropped active support in #115 but there are still a bunch of uses.
Specifically: `blank?`, `present?`, `camelcase`, `classify`, and `ActiveSupport::Concern`.
PR contains:
- revert: drop active support dependency
- use standard ruby `start_with`
- use standard ruby `forwardable`

Revert drop activesupport dependency

---

lib/manageiq/api/client/connection.rb

Before
======
If connecting to a host and a firewall blocks the message, The message would be empty and this would throw a strange exception.
```
lib/manageiq/api/client/connection.rb:112:in `raise': exception class/object expected (TypeError)
raise @error.message
^^^^^^^^^^^^^^
from lib/manageiq/api/client/connection.rb:112:in `check_response'
from lib/manageiq/api/client/connection.rb:103:in `send_request'
from lib/manageiq/api/client/connection.rb:24:in `get'
from lib/manageiq/api/client/client.rb:37:in `load_definitions'
from lib/manageiq/api/client/client.rb:62:in `reconnect'
from lib/manageiq/api/client/client.rb:33:in `initialize'
```
After
=====
If the message is empty, give some message and raise original exception
```
lib/manageiq/api/client/connection.rb:114:in …
```

Raise exceptions on empty responses

---

.github/workflows/ci.yaml
lib/manageiq/api/client.rb
lib/manageiq/api/client/connection.rb
manageiq-api-client.gemspec

faraday 2.0 uses different middleware.
Upgraded to use follow_redirects.
faraday 2.0 has been split up to use many http client libraries Using net-http, so this avoids requiring a dozen adapter gems
---
I would like to test this with tasks to ensure it all still works
Faraday 2.0 only supports ruby 3.0 and higher. had to drop testing (and supporting) ruby 2.7

upgrade faraday from 1.0 to 2.0

---

lib/manageiq/api/client/connection.rb
manageiq-api-client.gemspec

Support faraday 1.0 and 2.0

---

.github/workflows/ci.yaml
Gemfile
manageiq-api-client.gemspec

Drop end of life rubies and rails and add new versions
Ensure we're testing and supporting community supported versions.
Drop:
* rails 6.0
* rails 6.1
Add:
* ruby 3.2
* ruby 3.3
* rails 7.1
* rails 7.2
Note: ruby 3.0 is not difficult to keep maintaining for now but it's on the chopping block.

Use core minimum but allow 7.0/7.1/7.2 since core sets upper limit

---

lib/manageiq/api/client.rb
spec/spec_helper.rb

Require logger due to active_support breaking on Rails <= 7.0. See https://github.com/rails/rails/pull/54264
@jrafanie Please review.

Fix issues where active_support does not require logger properly
